# app/config/security.yml

security:
    encoders:

        UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ENTITY_MANAGER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_ENTITY_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /

    access_control:
        - { path: ^/admin, roles: ROLE_ENTITY_MANAGER }
