<?php

namespace BackendBundle\Repository;

/**
 * BureauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BureauRepository extends \Doctrine\ORM\EntityRepository
{
}
