<?php

namespace AssociatifBundle\Repository;

/**
 * BenevoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BenevoleRepository extends \Doctrine\ORM\EntityRepository
{
}
