<?php

namespace TerritoryBundle\Repository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuneRepository extends \Doctrine\ORM\EntityRepository
{
}
