<?php

namespace TerritoryBundle\Repository;

/**
 * MairieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MairieRepository extends \Doctrine\ORM\EntityRepository
{
}
