<?php

namespace TerritoryBundle\Repository;

/**
 * TerritoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerritoireRepository extends \Doctrine\ORM\EntityRepository
{
}
