<?php

namespace TerritoryBundle\Repository;

/**
 * TerritoryCommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerritoryCommuneRepository extends \Doctrine\ORM\EntityRepository
{
}
